import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const GENERATED_HEADER = `// This file is generated by \`npm run types:supabase\`.
// Do not edit it by hand.

`;
const outputPath = resolve('src/types/supabase.ts');
const checkOnly = process.argv.includes('--check');
const cliPath = resolve('node_modules/supabase/dist/supabase.js');

function generateTypes() {
  try {
    const generated = execFileSync(
      process.execPath,
      [cliPath, 'gen', 'types', 'typescript', '--local', '--schema', 'public'],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }
    );
    return `${GENERATED_HEADER}${generated.replace(/\r\n/g, '\n').trimEnd()}\n`;
  } catch (error) {
    const details = error.stderr?.toString().trim() || error.message;
    throw new Error(
      `Unable to generate Supabase types. Start the local stack and run ` +
      `\`npx supabase db reset\` first.\n${details}`
    );
  }
}

const generatedTypes = generateTypes();

if (!checkOnly) {
  writeFileSync(outputPath, generatedTypes, 'utf8');
  console.log(`Generated ${outputPath}`);
  process.exit(0);
}

const tempDirectory = mkdtempSync(join(tmpdir(), 'camping-dashboard-supabase-types-'));
const tempPath = join(tempDirectory, 'supabase.ts');

try {
  writeFileSync(tempPath, generatedTypes, 'utf8');
  const committedTypes = readFileSync(outputPath, 'utf8').replace(/\r\n/g, '\n');
  const candidateTypes = readFileSync(tempPath, 'utf8');

  if (committedTypes !== candidateTypes) {
    console.error(
      'Generated Supabase types are stale. Run `npm run types:supabase` and commit the result.'
    );
    process.exitCode = 1;
  } else {
    console.log('Generated Supabase types are current.');
  }
} finally {
  rmSync(tempDirectory, { recursive: true, force: true });
}
