// This file is generated by `npm run types:supabase`.
// Do not edit it by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      alert_refresh_state: {
        Row: {
          attempt_count: number
          created_at: string
          last_attempt_at: string | null
          last_error_code: string | null
          last_error_summary: string | null
          last_fingerprint: string | null
          last_success_at: string | null
          locked_at: string | null
          locked_by: string | null
          next_refresh_at: string
          provider: string
          provider_external_id: string
          status: string
          trip_id: string
          unsupported_reason: string | null
          updated_at: string
        }
        Insert: {
          attempt_count?: number
          created_at?: string
          last_attempt_at?: string | null
          last_error_code?: string | null
          last_error_summary?: string | null
          last_fingerprint?: string | null
          last_success_at?: string | null
          locked_at?: string | null
          locked_by?: string | null
          next_refresh_at?: string
          provider: string
          provider_external_id: string
          status?: string
          trip_id: string
          unsupported_reason?: string | null
          updated_at?: string
        }
        Update: {
          attempt_count?: number
          created_at?: string
          last_attempt_at?: string | null
          last_error_code?: string | null
          last_error_summary?: string | null
          last_fingerprint?: string | null
          last_success_at?: string | null
          locked_at?: string | null
          locked_by?: string | null
          next_refresh_at?: string
          provider?: string
          provider_external_id?: string
          status?: string
          trip_id?: string
          unsupported_reason?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "alert_refresh_state_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      alerts: {
        Row: {
          acknowledged_at: string | null
          body: string
          category: string
          created_at: string
          dismissed_at: string | null
          effective_at: string | null
          expires_at: string | null
          external_id: string
          fingerprint: string | null
          id: string
          is_active: boolean
          issued_at: string | null
          last_seen_at: string | null
          provider: string
          provider_updated_at: string | null
          resolved_at: string | null
          severity: string
          source: string
          source_url: string | null
          status: string
          title: string
          trip_id: string
          updated_at: string
        }
        Insert: {
          acknowledged_at?: string | null
          body: string
          category: string
          created_at?: string
          dismissed_at?: string | null
          effective_at?: string | null
          expires_at?: string | null
          external_id: string
          fingerprint?: string | null
          id?: string
          is_active?: boolean
          issued_at?: string | null
          last_seen_at?: string | null
          provider: string
          provider_updated_at?: string | null
          resolved_at?: string | null
          severity?: string
          source: string
          source_url?: string | null
          status: string
          title: string
          trip_id: string
          updated_at?: string
        }
        Update: {
          acknowledged_at?: string | null
          body?: string
          category?: string
          created_at?: string
          dismissed_at?: string | null
          effective_at?: string | null
          expires_at?: string | null
          external_id?: string
          fingerprint?: string | null
          id?: string
          is_active?: boolean
          issued_at?: string | null
          last_seen_at?: string | null
          provider?: string
          provider_updated_at?: string | null
          resolved_at?: string | null
          severity?: string
          source?: string
          source_url?: string | null
          status?: string
          title?: string
          trip_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "alerts_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      astro_data: {
        Row: {
          blue_hour_end: string | null
          golden_hour_end: string | null
          golden_hour_start: string | null
          milky_way_visibility: string | null
          moon_illumination: number | null
          moon_phase: string | null
          stargazing_notes: string | null
          trip_id: string
          updated_at: string | null
        }
        Insert: {
          blue_hour_end?: string | null
          golden_hour_end?: string | null
          golden_hour_start?: string | null
          milky_way_visibility?: string | null
          moon_illumination?: number | null
          moon_phase?: string | null
          stargazing_notes?: string | null
          trip_id: string
          updated_at?: string | null
        }
        Update: {
          blue_hour_end?: string | null
          golden_hour_end?: string | null
          golden_hour_start?: string | null
          milky_way_visibility?: string | null
          moon_illumination?: number | null
          moon_phase?: string | null
          stargazing_notes?: string | null
          trip_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "astro_data_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: true
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      crew_members: {
        Row: {
          canoe_number: number | null
          id: string
          load_item: string | null
          load_weight_kg: number | null
          name: string
          notes: string | null
          role: string | null
          trip_id: string
          trip_member_id: string | null
        }
        Insert: {
          canoe_number?: number | null
          id?: string
          load_item?: string | null
          load_weight_kg?: number | null
          name: string
          notes?: string | null
          role?: string | null
          trip_id: string
          trip_member_id?: string | null
        }
        Update: {
          canoe_number?: number | null
          id?: string
          load_item?: string | null
          load_weight_kg?: number | null
          name?: string
          notes?: string | null
          role?: string | null
          trip_id?: string
          trip_member_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "crew_members_same_trip_member_fkey"
            columns: ["trip_id", "trip_member_id"]
            isOneToOne: false
            referencedRelation: "trip_members"
            referencedColumns: ["trip_id", "id"]
          },
          {
            foreignKeyName: "crew_members_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      gear_items: {
        Row: {
          acquired: boolean
          category: string | null
          id: string
          name: string
          notes: string | null
          owner: string | null
          packed: boolean | null
          priority: string | null
          responsible_crew_member_id: string | null
          trip_id: string
          weight_kg: number | null
        }
        Insert: {
          acquired?: boolean
          category?: string | null
          id?: string
          name: string
          notes?: string | null
          owner?: string | null
          packed?: boolean | null
          priority?: string | null
          responsible_crew_member_id?: string | null
          trip_id: string
          weight_kg?: number | null
        }
        Update: {
          acquired?: boolean
          category?: string | null
          id?: string
          name?: string
          notes?: string | null
          owner?: string | null
          packed?: boolean | null
          priority?: string | null
          responsible_crew_member_id?: string | null
          trip_id?: string
          weight_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "gear_items_same_trip_responsible_crew_fkey"
            columns: ["trip_id", "responsible_crew_member_id"]
            isOneToOne: false
            referencedRelation: "crew_members"
            referencedColumns: ["trip_id", "id"]
          },
          {
            foreignKeyName: "gear_items_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      meals: {
        Row: {
          assigned_to: string | null
          calories: number | null
          day_number: number | null
          id: string
          meal_type: string | null
          notes: string | null
          prep_crew_member_id: string | null
          prep_type: string | null
          title: string | null
          trip_id: string
        }
        Insert: {
          assigned_to?: string | null
          calories?: number | null
          day_number?: number | null
          id?: string
          meal_type?: string | null
          notes?: string | null
          prep_crew_member_id?: string | null
          prep_type?: string | null
          title?: string | null
          trip_id: string
        }
        Update: {
          assigned_to?: string | null
          calories?: number | null
          day_number?: number | null
          id?: string
          meal_type?: string | null
          notes?: string | null
          prep_crew_member_id?: string | null
          prep_type?: string | null
          title?: string | null
          trip_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "meals_same_trip_prep_crew_fkey"
            columns: ["trip_id", "prep_crew_member_id"]
            isOneToOne: false
            referencedRelation: "crew_members"
            referencedColumns: ["trip_id", "id"]
          },
          {
            foreignKeyName: "meals_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      offline_status: {
        Row: {
          daily_vehicle_permit_saved: boolean | null
          emergency_contact_ready: boolean | null
          maps_cached: boolean | null
          permit_saved: boolean | null
          route_downloaded: boolean | null
          satellite_device_connected: boolean | null
          satellite_device_name: string | null
          trip_id: string
          updated_at: string | null
        }
        Insert: {
          daily_vehicle_permit_saved?: boolean | null
          emergency_contact_ready?: boolean | null
          maps_cached?: boolean | null
          permit_saved?: boolean | null
          route_downloaded?: boolean | null
          satellite_device_connected?: boolean | null
          satellite_device_name?: string | null
          trip_id: string
          updated_at?: string | null
        }
        Update: {
          daily_vehicle_permit_saved?: boolean | null
          emergency_contact_ready?: boolean | null
          maps_cached?: boolean | null
          permit_saved?: boolean | null
          route_downloaded?: boolean | null
          satellite_device_connected?: boolean | null
          satellite_device_name?: string | null
          trip_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "offline_status_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: true
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      park_intel: {
        Row: {
          custom_notes: string | null
          fire_restriction: string | null
          firewood_percent: number | null
          ranger_station: string | null
          trip_id: string
          updated_at: string | null
          water_notes: string | null
          wildlife_notes: string | null
        }
        Insert: {
          custom_notes?: string | null
          fire_restriction?: string | null
          firewood_percent?: number | null
          ranger_station?: string | null
          trip_id: string
          updated_at?: string | null
          water_notes?: string | null
          wildlife_notes?: string | null
        }
        Update: {
          custom_notes?: string | null
          fire_restriction?: string | null
          firewood_percent?: number | null
          ranger_station?: string | null
          trip_id?: string
          updated_at?: string | null
          water_notes?: string | null
          wildlife_notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "park_intel_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: true
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      prep_feed_items: {
        Row: {
          caption: string | null
          category: string
          created_at: string
          id: string
          image_url: string | null
          storage_path: string | null
          trip_id: string
          uploaded_by: string
        }
        Insert: {
          caption?: string | null
          category?: string
          created_at?: string
          id?: string
          image_url?: string | null
          storage_path?: string | null
          trip_id: string
          uploaded_by?: string
        }
        Update: {
          caption?: string | null
          category?: string
          created_at?: string
          id?: string
          image_url?: string | null
          storage_path?: string | null
          trip_id?: string
          uploaded_by?: string
        }
        Relationships: [
          {
            foreignKeyName: "prep_feed_items_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      prep_feed_storage_cleanup_jobs: {
        Row: {
          attempt_count: number
          completed_at: string | null
          created_at: string
          failed_at: string | null
          id: string
          item_id: string | null
          last_attempt_at: string | null
          last_error_code: string | null
          last_error_summary: string | null
          locked_at: string | null
          locked_by: string | null
          next_attempt_at: string
          status: string
          storage_path: string
          trip_id: string
        }
        Insert: {
          attempt_count?: number
          completed_at?: string | null
          created_at?: string
          failed_at?: string | null
          id?: string
          item_id?: string | null
          last_attempt_at?: string | null
          last_error_code?: string | null
          last_error_summary?: string | null
          locked_at?: string | null
          locked_by?: string | null
          next_attempt_at?: string
          status?: string
          storage_path: string
          trip_id: string
        }
        Update: {
          attempt_count?: number
          completed_at?: string | null
          created_at?: string
          failed_at?: string | null
          id?: string
          item_id?: string | null
          last_attempt_at?: string | null
          last_error_code?: string | null
          last_error_summary?: string | null
          locked_at?: string | null
          locked_by?: string | null
          next_attempt_at?: string
          status?: string
          storage_path?: string
          trip_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "prep_feed_storage_cleanup_jobs_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      settings: {
        Row: {
          manual_theme_override: string | null
          preferred_units: string | null
          show_astro: boolean | null
          show_crew: boolean | null
          show_meals: boolean | null
          show_offline: boolean | null
          theme_variant: string
          trip_id: string
        }
        Insert: {
          manual_theme_override?: string | null
          preferred_units?: string | null
          show_astro?: boolean | null
          show_crew?: boolean | null
          show_meals?: boolean | null
          show_offline?: boolean | null
          theme_variant?: string
          trip_id: string
        }
        Update: {
          manual_theme_override?: string | null
          preferred_units?: string | null
          show_astro?: boolean | null
          show_crew?: boolean | null
          show_meals?: boolean | null
          show_offline?: boolean | null
          theme_variant?: string
          trip_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "settings_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: true
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      timeline_events: {
        Row: {
          day_number: number | null
          details: string | null
          event_time: string | null
          id: string
          phase: string | null
          sort_order: number | null
          title: string | null
          trip_id: string | null
        }
        Insert: {
          day_number?: number | null
          details?: string | null
          event_time?: string | null
          id?: string
          phase?: string | null
          sort_order?: number | null
          title?: string | null
          trip_id?: string | null
        }
        Update: {
          day_number?: number | null
          details?: string | null
          event_time?: string | null
          id?: string
          phase?: string | null
          sort_order?: number | null
          title?: string | null
          trip_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "timeline_events_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      trip_members: {
        Row: {
          created_at: string | null
          id: string
          role: string
          trip_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          role?: string
          trip_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          role?: string
          trip_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "trip_members_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      trips: {
        Row: {
          campsite_label: string | null
          campsite_latitude: number | null
          campsite_longitude: number | null
          campsite_osm_id: string | null
          campsite_source: string | null
          country_code: string | null
          created_at: string | null
          deletion_pending_at: string | null
          deletion_token: string | null
          distance_km: number | null
          end_date: string | null
          id: string
          lake_name: string | null
          launch_lat: number | null
          launch_lng: number | null
          launch_point_name: string | null
          map_style: string | null
          name: string
          notes: string | null
          park_alert_external_id: string | null
          park_alert_provider: string | null
          park_name: string | null
          region_code: string | null
          site_lat: number | null
          site_lng: number | null
          site_name: string | null
          start_date: string | null
          theme_mode: string | null
          updated_at: string | null
          weather_alert_provider: string | null
          weather_alert_region_code: string | null
        }
        Insert: {
          campsite_label?: string | null
          campsite_latitude?: number | null
          campsite_longitude?: number | null
          campsite_osm_id?: string | null
          campsite_source?: string | null
          country_code?: string | null
          created_at?: string | null
          deletion_pending_at?: string | null
          deletion_token?: string | null
          distance_km?: number | null
          end_date?: string | null
          id: string
          lake_name?: string | null
          launch_lat?: number | null
          launch_lng?: number | null
          launch_point_name?: string | null
          map_style?: string | null
          name: string
          notes?: string | null
          park_alert_external_id?: string | null
          park_alert_provider?: string | null
          park_name?: string | null
          region_code?: string | null
          site_lat?: number | null
          site_lng?: number | null
          site_name?: string | null
          start_date?: string | null
          theme_mode?: string | null
          updated_at?: string | null
          weather_alert_provider?: string | null
          weather_alert_region_code?: string | null
        }
        Update: {
          campsite_label?: string | null
          campsite_latitude?: number | null
          campsite_longitude?: number | null
          campsite_osm_id?: string | null
          campsite_source?: string | null
          country_code?: string | null
          created_at?: string | null
          deletion_pending_at?: string | null
          deletion_token?: string | null
          distance_km?: number | null
          end_date?: string | null
          id?: string
          lake_name?: string | null
          launch_lat?: number | null
          launch_lng?: number | null
          launch_point_name?: string | null
          map_style?: string | null
          name?: string
          notes?: string | null
          park_alert_external_id?: string | null
          park_alert_provider?: string | null
          park_name?: string | null
          region_code?: string | null
          site_lat?: number | null
          site_lng?: number | null
          site_name?: string | null
          start_date?: string | null
          theme_mode?: string | null
          updated_at?: string | null
          weather_alert_provider?: string | null
          weather_alert_region_code?: string | null
        }
        Relationships: []
      }
      weather_current: {
        Row: {
          condition_label: string | null
          humidity: number | null
          icon: string | null
          moonset_time: string | null
          rain_chance: number | null
          sunrise_time: string | null
          sunset_time: string | null
          temperature_c: number | null
          trip_id: string
          updated_at: string | null
          visibility: number | null
          wind_kph: number | null
        }
        Insert: {
          condition_label?: string | null
          humidity?: number | null
          icon?: string | null
          moonset_time?: string | null
          rain_chance?: number | null
          sunrise_time?: string | null
          sunset_time?: string | null
          temperature_c?: number | null
          trip_id: string
          updated_at?: string | null
          visibility?: number | null
          wind_kph?: number | null
        }
        Update: {
          condition_label?: string | null
          humidity?: number | null
          icon?: string | null
          moonset_time?: string | null
          rain_chance?: number | null
          sunrise_time?: string | null
          sunset_time?: string | null
          temperature_c?: number | null
          trip_id?: string
          updated_at?: string | null
          visibility?: number | null
          wind_kph?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "weather_current_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: true
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      weather_forecast: {
        Row: {
          condition_label: string | null
          forecast_date: string
          high_c: number | null
          icon: string | null
          id: string
          low_c: number | null
          rain_chance: number | null
          trip_id: string
          wind_kph: number | null
        }
        Insert: {
          condition_label?: string | null
          forecast_date: string
          high_c?: number | null
          icon?: string | null
          id: string
          low_c?: number | null
          rain_chance?: number | null
          trip_id: string
          wind_kph?: number | null
        }
        Update: {
          condition_label?: string | null
          forecast_date?: string
          high_c?: number | null
          icon?: string | null
          id?: string
          low_c?: number | null
          rain_chance?: number | null
          trip_id?: string
          wind_kph?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "weather_forecast_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      weather_refresh_state: {
        Row: {
          attempt_count: number
          created_at: string
          last_attempt_at: string | null
          last_error_code: string | null
          last_error_summary: string | null
          last_success_at: string | null
          locked_at: string | null
          locked_by: string | null
          next_refresh_at: string
          payload_fingerprint: string | null
          provider: string | null
          provider_generated_at: string | null
          provider_timezone: string | null
          request_fingerprint: string | null
          source_observed_at: string | null
          status: string
          trip_id: string
          updated_at: string
          utc_offset_seconds: number | null
        }
        Insert: {
          attempt_count?: number
          created_at?: string
          last_attempt_at?: string | null
          last_error_code?: string | null
          last_error_summary?: string | null
          last_success_at?: string | null
          locked_at?: string | null
          locked_by?: string | null
          next_refresh_at?: string
          payload_fingerprint?: string | null
          provider?: string | null
          provider_generated_at?: string | null
          provider_timezone?: string | null
          request_fingerprint?: string | null
          source_observed_at?: string | null
          status?: string
          trip_id: string
          updated_at?: string
          utc_offset_seconds?: number | null
        }
        Update: {
          attempt_count?: number
          created_at?: string
          last_attempt_at?: string | null
          last_error_code?: string | null
          last_error_summary?: string | null
          last_success_at?: string | null
          locked_at?: string | null
          locked_by?: string | null
          next_refresh_at?: string
          payload_fingerprint?: string | null
          provider?: string | null
          provider_generated_at?: string | null
          provider_timezone?: string | null
          request_fingerprint?: string | null
          source_observed_at?: string | null
          status?: string
          trip_id?: string
          updated_at?: string
          utc_offset_seconds?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "weather_refresh_state_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: true
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      begin_trip_deletion: { Args: { p_trip_id: string }; Returns: string }
      claim_due_trip_alerts: {
        Args: {
          p_batch_size?: number
          p_stale_after_seconds?: number
          p_worker_id: string
        }
        Returns: {
          attempt_count: number
          country_code: string
          provider: string
          provider_external_id: string
          region_code: string
          trip_id: string
        }[]
      }
      claim_due_trip_weather: {
        Args: {
          p_batch_size?: number
          p_stale_after_seconds?: number
          p_worker_id: string
        }
        Returns: {
          attempt_count: number
          latitude: number
          longitude: number
          timezone: string
          trip_id: string
        }[]
      }
      claim_prep_feed_storage_cleanup_jobs: {
        Args: {
          p_batch_size?: number
          p_stale_after_seconds?: number
          p_worker_id: string
        }
        Returns: {
          attempt_count: number
          id: string
          storage_path: string
          trip_id: string
        }[]
      }
      claim_trip_alerts_manual: {
        Args: {
          p_cooldown_seconds?: number
          p_stale_after_seconds?: number
          p_trip_id: string
          p_worker_id: string
        }
        Returns: {
          attempt_count: number
          country_code: string
          provider: string
          provider_external_id: string
          region_code: string
          trip_id: string
        }[]
      }
      claim_trip_weather_manual: {
        Args: {
          p_cooldown_seconds?: number
          p_stale_after_seconds?: number
          p_trip_id: string
          p_worker_id: string
        }
        Returns: {
          attempt_count: number
          latitude: number
          longitude: number
          timezone: string
          trip_id: string
        }[]
      }
      complete_prep_feed_storage_cleanup_job: {
        Args: { p_job_id: string; p_worker_id: string }
        Returns: boolean
      }
      complete_trip_deletion: {
        Args: { p_deletion_token: string; p_trip_id: string }
        Returns: boolean
      }
      create_trip: {
        Args: {
          p_campsite_label?: string
          p_campsite_latitude: number
          p_campsite_longitude: number
          p_campsite_osm_id?: string
          p_campsite_source?: string
          p_end_date: string
          p_lake_name?: string
          p_name: string
          p_park_name?: string
          p_site_name?: string
          p_start_date: string
        }
        Returns: string
      }
      fail_prep_feed_storage_cleanup_job: {
        Args: {
          p_error_code: string
          p_error_summary: string
          p_job_id: string
          p_worker_id: string
        }
        Returns: boolean
      }
      fail_trip_alerts: {
        Args: {
          p_error_code: string
          p_error_summary: string
          p_provider: string
          p_trip_id: string
          p_worker_id: string
        }
        Returns: boolean
      }
      fail_trip_weather: {
        Args: {
          p_error_code: string
          p_error_summary: string
          p_trip_id: string
          p_worker_id: string
        }
        Returns: boolean
      }
      get_prep_feed_storage_cleanup_summary: { Args: never; Returns: Json }
      persist_trip_alerts: {
        Args: {
          p_payload: Json
          p_provider: string
          p_trip_id: string
          p_worker_id: string
        }
        Returns: string
      }
      persist_trip_weather: {
        Args: { p_payload: Json; p_trip_id: string; p_worker_id: string }
        Returns: string
      }
      replace_prep_feed_image: {
        Args: {
          p_actor_user_id: string
          p_image_url: string
          p_item_id: string
          p_storage_path: string
        }
        Returns: Json
      }
      retry_failed_prep_feed_storage_cleanup_job: {
        Args: { p_job_id: string }
        Returns: boolean
      }
      retry_prep_feed_storage_cleanup_job: {
        Args: {
          p_error_code: string
          p_error_summary: string
          p_job_id: string
          p_next_attempt_at: string
          p_worker_id: string
        }
        Returns: boolean
      }
      retry_trip_alerts: {
        Args: {
          p_error_code: string
          p_error_summary: string
          p_provider: string
          p_trip_id: string
          p_worker_id: string
        }
        Returns: boolean
      }
      retry_trip_weather: {
        Args: {
          p_error_code: string
          p_error_summary: string
          p_trip_id: string
          p_worker_id: string
        }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
