import {POST,PRE,VERSIONS,POST_SENTINELS,SCHEMA_FINGERPRINT} from './postMigrationContract.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {STAGING_REF as ref,SENTINELS,PROTECTED_SCHEMAS,IDENTITY_SQL,backendRole,projectMatches,provenance,sqlEvidence,identityVerdict,probesAgree,validIdentityEvidence} from './sqlIdentity.mjs';
const row={migration_history:VERSIONS,post_schema_hash:SCHEMA_FINGERPRINT,post_sentinels:Object.fromEntries(Object.keys(POST_SENTINELS).map(s=>[s,true])),database_name:'postgres',database_user:'postgres',session_user:'postgres',read_only:'on',system_id:'1234',schema_hash:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',sentinels:Object.fromEntries(SENTINELS.map(s=>[s,false]))};
const sql=(patch={})=>sqlEvidence(JSON.stringify({...row,...patch}));
const signals={management_project_match:true,pooler_tenant_match:true,api_credentials_project_match:true,tls_verified:true};
const project={id:ref,name:'field-protocol-staging',status:'ACTIVE_HEALTHY',organization_id:'qvhhhjlpntbtctqinayz',database:{host:`db.${ref}.supabase.co`}};
test('unqualified postgres backend passes qualified staging routing',()=>{assert.equal(backendRole(`postgres.${ref}`),'postgres');assert.ok(validIdentityEvidence(identityVerdict(signals,sql(),true)));});
test('exact active metadata',()=>{assert.ok(projectMatches(project));for(const key of Object.keys(project))assert.equal(projectMatches({...project,[key]:'wrong'}),false);});
for(const protectedRef of ['gdsmyxzqtmhwbcyobzou','rmfhueseulevyvetblnn'])test('reject protected routing '+protectedRef,()=>assert.throws(()=>backendRole(`postgres.${protectedRef}`)));
for(const sentinel of Object.keys(POST_SENTINELS))test('reject sentinel '+sentinel,()=>assert.equal(sql({post_sentinels:{...row.post_sentinels,[sentinel]:false}}).passed,false));
for(const [name,hash] of Object.entries(PROTECTED_SCHEMAS))test('reject protected schema '+name,()=>assert.equal(sql({schema_hash:hash}).evidence.protected_schema_match,name));
for(const key of ['database_name','database_user','session_user','read_only','system_id','schema_hash','post_sentinels'])test('reject wrong SQL '+key,()=>assert.equal(sql({[key]:'wrong'}).passed,false));
test('A B must agree',()=>{assert.ok(probesAgree(sql(),sql()));assert.equal(probesAgree(sql(),sql({system_id:'5678'})),false);assert.equal(probesAgree(sql(),sql({schema_hash:'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'})),false);});
test('every independent signal required',()=>{for(const key of Object.keys(signals))assert.equal(identityVerdict({...signals,[key]:false},sql(),true).final_identity_verdict,'FAIL');assert.equal(identityVerdict(signals,sql(),false).final_identity_verdict,'FAIL');});
const now=Date.now(),host='aws-0-ca-central-1.pooler.supabase.com';
const receipt={version:2,ready:true,ref,state:'ACTIVE_HEALTHY',timestampUtc:new Date(now).toISOString(),poolerEndpoint:`/projects/${ref}/config/database/pooler`,poolerStatus:200,host,user:`postgres.${ref}`,database:'postgres',port:5432,apiEndpoint:`/projects/${ref}/api-keys?reveal=true`,apiStatus:200,generation:'legacy'};
test('fresh exact endpoint provenance',()=>assert.deepEqual(provenance(receipt,host,now),{pooler_tenant_match:true,api_credentials_project_match:true}));
test('stale future or wrong receipt cannot authorize',()=>{for(const patch of [{ref:'protected'},{ready:false},{version:1},{state:'INACTIVE'},{timestampUtc:new Date(now-600001).toISOString()},{timestampUtc:new Date(now+1).toISOString()}])assert.ok(Object.values(provenance({...receipt,...patch},host,now)).every(v=>v===false));});
test('wrong provider and key endpoints rejected',()=>{assert.equal(provenance({...receipt,poolerEndpoint:'/projects/wrong/config/database/pooler'},host,now).pooler_tenant_match,false);assert.equal(provenance({...receipt,apiEndpoint:'/projects/wrong/api-keys?reveal=true'},host,now).api_credentials_project_match,false);});
test('sanitized unknown SQL values never escape',()=>assert.ok(!JSON.stringify(sql({database_user:'SENTINEL_SECRET',database_name:'SENTINEL_SECRET'}).evidence).includes('SENTINEL_SECRET')));
test('explicit read only transaction and repository derived sentinels',()=>{assert.match(IDENTITY_SQL,/^BEGIN READ ONLY;/);assert.match(IDENTITY_SQL,/COMMIT;$/);const migration=readFileSync(new URL('../../supabase/migrations/20260710135251_006_fix_trip_members_rls_recursion.sql',import.meta.url),'utf8');for(const s of SENTINELS)assert.ok(migration.includes(s));});
